from pathlib import PurePath

GENERATED_PYTHON_ENVIRONMENT_DIRECTORY_NAMES = frozenset({".venv"})


def is_generated_python_artifact(path: PurePath) -> bool:
    """Return whether a relative path is interpreter-generated bytecode."""
    return "__pycache__" in path.parts
