from pathlib import PurePath


def is_generated_python_artifact(path: PurePath) -> bool:
    """Return whether a relative path is interpreter-generated bytecode."""
    return "__pycache__" in path.parts
